### PR TITLE
PDS4 Information Model Release 1.18.0.0

### PR DESCRIPTION
**Pull request by pds-ops**
Automated tagging of repo for nominal release of sub-model for PDS4 Release 1.18.0.0

### CODE REVIEW

**Comment by jordanpadams** [comment]
@thareUSGS not sure I understand? but this PR will automatically tag a new release of CART for PDS4 version 1.17 and 1.18 with whatever is on main (in your case v1960).

are you saying there are updates you would like included that are on some other branch somewhere?

**Comment by thareUSGS** [comment]
@jordanpadams You answered it. I was worried that a new release was not going to get pulled (since I never made a branch with release in the name). But it appears you are doing that for us for the IM. All good here.

**Comment by jordanpadams** [comment]
@thareUSGS copy. i will talk about this more on Monday, but that is ideal lifecycle for a discipline LDD/sub-model. make updates during the 6-month "development" period. then at build time, we will prep a release, and the steward can merge it to tag it. this will then get grabbed up when we generate all our documentation and put everything online.

**Comment by jordanpadams** [comment]
note: I am merging all these this time around, but in the future, all Stewards are responsible for reviewing the Pull Request EN will tag and merging.

**Comment by jordanpadams** [comment]
@wkiri @thareUSGS updated the docs. let me know if that helps at all. (not that anyone really reads it 😄 )

**Comment by wkiri** [comment]
Thanks @jordanpadams !  Would you like to update
"By default, all Discipline LDDs will be built at the time of PDS4 IM Release."
to something like
"By default, all Discipline LDDs will be built at the time of PDS4 IM Release, and the Steward is responsible for reviewing and approving the associated pull request to generate the release."?

**Comment by jordanpadams** [comment]
@wkiri actually it looks like the page took a while to update. Can you try again and refresh your page?

**Comment by wkiri** [comment]
@jordanpadams Fantastic!  Your edits make this very clear.  Thank you!

**Comment by jordanpadams** [comment]
Thanks @wkiri

**Pull request merged**
